name: turbine_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8            # Preferred Python version
  - jupyter               # Jupyter Notebook
  - pandas                # Data analysis library
  - ipykernel             # Allows the Conda environment to appear as a Jupyter kernel
  - notebook              # Jupyter Notebook interface
  - numpy                 # Numerical computations
  - matplotlib            # Basic plotting
  - dataprep              # Exploratory Data Analysis package
  - cookiecutter          # File structure creator
  - hydra-core            # Library that allows you to access parameters from a configuration file inside a Python script
  - scikit-learn          # For performating PCA analysis