hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

data:
  raw: 
    fault: data/raw/fault_data.csv
    scada: data/raw/scada_data.csv
    status: data/raw/status_data.csv
  processed:
  final: